CREATE TABLE CLIENTS(
    IdClient INT PRIMARY KEY INDENTITY,
    Name VARCHAR(30) NOT NULL,
    Channel VARCHAR(20) NOT NULL,
)
GO

INSERT INTO CLIENTS(Name , Channel) VALUES('Gabriel' , 'TopVideos')
GO

SELECT * FROM CLIENTS